stages:
  - lint
  - build
  - build_docker
  - scan
  - deploy

# =====================
# Lint Jobs
# =====================
lint_backend:
  image: python:3.11
  stage: lint
  script:
    - cd backend
    - pip install -r requirements.txt
    - pylint . || true
  allow_failure: true
  only:
    - yasmina-main

lint_frontend:
  image: node:18
  stage: lint
  script:
    - cd frontend
    - npm install
    - npm run lint || true
  allow_failure: true
  only:
    - yasmina-main

# =====================
# Build Jobs
# =====================
build_backend:
  image: python:3.11
  stage: build
  script:
    - cd backend
    - pip install -r requirements.txt
  only:
    - yasmina-main

build_frontend:
  image: node:18
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/build
  only:
    - yasmina-main

# =====================
# Build Docker Jobs + Push to Docker Hub
# =====================
build_docker_backend:
  image: docker:24.0.2
  services:
    - docker:dind
  stage: build_docker
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin || true
    - docker build -t yasmina504/backend backend/ || true
    - docker push yasmina504/backend || true
  allow_failure: true
  only:
    - yasmina-main

build_docker_frontend:
  image: docker:24.0.2
  services:
    - docker:dind
  stage: build_docker
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin || true
    - docker build -t yasmina504/frontend frontend/ || true
    - docker push yasmina504/frontend || true
  allow_failure: true
  only:
    - yasmina-main

# =====================
# Scan Jobs (Trivial)
# =====================
scan_backend:
  image: docker:24.0.2
  services:
    - docker:dind
  stage: scan
  script:
    - docker pull yasmina504/backend || true
    - docker images | grep backend
  allow_failure: true
  only:
    - yasmina-main

scan_frontend:
  image: docker:24.0.2
  services:
    - docker:dind
  stage: scan
  script:
    - docker pull yasmina504/frontend || true
    - docker images | grep frontend
  allow_failure: true
  only:
    - yasmina-main

# =====================
# Deploy with Ansible
# =====================
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache ansible openssh-client bash
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 172.16.60.128 >> ~/.ssh/known_hosts
  script:
    - ansible-playbook -i ansible/inventory ansible/deploy.yml -b
  when: always
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  only:
    - yasmina-main

