version: '3.9'

services:
  db:
    image: postgres:16
    container_name: tier-app-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: tierapp
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-db-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tier-app-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - backend-db-net
      - frontend-backend-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tier-app-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontend-backend-net

volumes:
  db-data:

networks:
  backend-db-net:
  frontend-backend-net:

