---
- name: Deploy 3-Tier App with Docker Compose
  hosts: app_server
  become: true

  vars:
    project_dir: /home/yasmina/tier-app

  tasks:
    - name: Create project directory on server
      file:
        path: "{{ project_dir }}"
        state: directory
        owner: yasmina
        group: yasmina
        mode: '0755'

    - name: Copy project files from local to server
      synchronize:
        src: "{{ playbook_dir }}/../"
        dest: "{{ project_dir }}/"
        recursive: yes
        delete: yes
      delegate_to: localhost
      become: false   # 👈 مهم عشان ما يطلبش sudo على جهازك

    - name: Run docker compose up
      shell: |
        docker compose -f {{ project_dir }}/docker-compose.yml up -d
      args:
        chdir: "{{ project_dir }}"

